### PR TITLE
Round_The_Corner script

### PR DESCRIPTION
**Pull request by zharovdv**
May be my script will be usefull for somebody else except me. This script could simplify polygon, align sides, unwrap bevels and round corners.

### CODE REVIEW

**Comment by antifar** [comment]
邮件已收到，祝好。^_^

**Comment by justinmassiot** [comment]
Hello @zharovdv ,
Thank you for this nice contribution!

Some suggestions before the merge:
- Would be great if you could create a README file which briefly explains what the script does and which includes your screen capture (example: https://github.com/Altium-Designer-addons/scripts-libraries/tree/master/Scripts%20-%20Misc/mil-mm-conv).
- If the script acts on polygons only, could you please consider renaming your script? Something like RoundPolygonCorners?
- Please make the naming consistent between the script files and their containing folder.

Thanks!

**Comment by zharovdv** [comment]
- Script renamed to RoundPolygonCorners
- Some kind of readme file added with basic description and GUI/feature screenshots

**Comment by zharovdv** [comment]
My screenshots were ugly, change them to git animation.

**Comment by justinmassiot** [comment]
Very nice! The GIF animation is a must.
Thanks! 😉

**Pull request merged**
