### PR TITLE
AutoPlaceSilkscreen_AnyAngle

### PR DESCRIPTION
**Pull request by RnDMonkey**
@coffeenmusic here is my initial effort toward supporting any-angle placement. If you have time to test it that would be good. I'll probably keep it in this branch for a little while until it's had some review and I've used it on larger projects.

My approach has two main aspects:

- Use the IPCB_ContourMaker2 and IPCB_ContourUtilities classes to create and detect overlaps between object outlines rather than using bounding boxes
- For component rotations that aren't multiples of 90°, temporarily rotate them to 0 to let designator autoposition work correctly

It still requires fine-tuning, but it's a start.
image

### CODE REVIEW

**Comment by coffeenmusic** [comment]
That's awesome! I wasn't even aware of the Contour classes. How did you find out about these, I don't see any info come up if I google them. I'll try to get some time soon to test this code out and let you know how it goes.

**Comment by RnDMonkey** [comment]
I believe @BrettLMiller pointed them out to me or pointed me in that direction with some forum comments. Once they were on my radar, I started exploring them using what was available in the SDK 4.0 source files. There might be more there in newer versions that remains entirely undocumented (for us outsiders, at least).

**Comment by justinmassiot** [comment]
Very nice, I think I'm gonna test it on my current project.

**Comment by RnDMonkey** [comment]
The glaring hole right now is that it doesn't have any contour-based implementation for components, so detecting the designator being under a component probably doesn't work. Of course, it usually hits something else first, but I can imagine it having some issues with large components that leave a lot of open space underneath.

**Comment by RnDMonkey** [comment]
> Very nice, I think I'm gonna test it on my current project.

@justinmassiot Awesome, let me know if you find any glaring issues.

**Comment by RnDMonkey** [comment]
@coffeenmusic I have a proposal for component body detection. 
- Potential issue: the eComponentBodyObject check looks for component bodies only on the mechanical layer chosen by the user in the GUI. At a minimum, this means you can only run the autoplacer on one side of the board at a time because you are forced to choose a single layer. At worst, the user chooses the wrong layer and there will be nothing to check against.
- Proposal: For any component, simply use the largest (by IPCB_ComponentBody.Area) component body it contains. IMO this can most likely be assumed to be the one we'd care about.

With this change I think I'd be able to wrap up this version.

What do you think?

**Comment by coffeenmusic** [comment]
I think that would work. I can't think off the top of my head what other component body objects there would be. If you make that change, I would be happy to test it on a few boards. Although, I thought the Contour classes you added solved that problem?

**Comment by RnDMonkey** [comment]
> Although, I thought the Contour classes you added solved that problem?
Not really. The contour still needs an object to draw around, and this is a question of how you get the object in the first place. Currently, when the spatial iterator is invoked for eComponentBodyObject, it filters by just the specified layer, regardless of whether there is actually any body on that layer.

**Comment by RnDMonkey** [comment]
@coffeenmusic okay, it's ready for testing now. The other significant change is that when placing only selected designators, selection order of the components affects placement order. I find this useful when placement order gets in its own way.

**Comment by RnDMonkey** [comment]
> I find this useful when placement order gets in its own way.
Before:
image

After:
image

**Comment by justinmassiot** [comment]
Hello everyone.

Script tested in Altium Designer 23.5.1-21 with a PCB of 381 components, but the `while` loop at line 1591 in function `Get_Iterator_Count` goes infinite. The components counter visible in the Messages panel goes far beyond 381!

This is very weird because:

- The iterator loop is written correctly
- It did work in the original version of AutoPlaceSilkscreen, in the exact same conditions

**Comment by RnDMonkey** [comment]
I'm pretty sure I broke it when I "fixed" the progress status update and
re-used calls to Get_Iterator_Count. I neglected to look inside that
function to see how it works, so I bet it's making the iterator lose its
place in the loop on line 2142

**Comment by coffeenmusic** [comment]
I just got around to testing. It looks like the call to GetLayerSet at line 790 is a typo and should be Get_LayerSet. I ran and got an error that it is undeclared.

**Comment by RnDMonkey** [comment]
> I just got around to testing. It looks like the call to GetLayerSet at line 790 is a typo and should be Get_LayerSet. I ran and got an error that it is undeclared.

Right you are. How'd it go otherwise?

**Comment by coffeenmusic** [comment]
I tested on several boards and I think everything was working as expected. 97% placed on a board with 142 components and 74% placed on a board with 1835 components.

**Comment by RnDMonkey** [comment]
Shall I go ahead and merge it then?

**Comment by coffeenmusic** [comment]
That sounds good to me.

**Comment by RnDMonkey** [comment]
@coffeenmusic cool, merge complete.

I also just want to say thank you very much for the very fine work you've put into this script and your sharing it with others. I've taken multiple pieces of code and inspiration from it for my QuickSilk script, and without your effort here I wouldn't have been able and inspired to push forward and make that script as good as it is in such a short time. Again, thank you!

-Ryan

**Comment by coffeenmusic** [comment]
That's awesome, I hadn't seen your QuickSilk script before. I'll have to give it a try. Also, I'm not sure I would call my hacky script "fine work", but I really appreciate it. It looks like I could probably learn more from looking over your code than you did from mine. Thank you for contributing as well!

**Pull request merged**
