### PR TITLE
Mechlayernames

### PR DESCRIPTION
**Pull request by BrettLMiller**
Script has existed for quite some time & original Is broken in AD17-AD19 & never implemented colour & mechanical pairs.
This version is a partial fix because only works up to eMechanical 32 & colour is supported up to eMech16. Other layers are ignored/not changed.
The scripting API does not appear to have support for the new AD19 layer-type & 1024 mechlayers so that is not handled.

### CODE REVIEW

**Comment by BrettLMiller** [comment]
The script works okay with AD17 to AD19 with some limitations; 32 mech layer max, no colour after eMech16 .
A third party AD19 user does not see any damage/problems with new 1024? max mech layer setup just it does nothing after eMech32.

I can not test old versions without installing & it is possible they will not run on/with my license server.
If that's not acceptable I can store this script in my github collection (with a warning!)
Maybe that's the best approach.

The reality is that no one using half the scripts because they don't know:-
- they exist
- how to use AD scripting
- how to use github
- who to ask to fix.

I've been helping script users in forums because I can see Altium leaving the scripting API on life support unless people start using it & then complaining about how bad it is.. 
Thanks
BrettM

**Comment by justinmassiot** [comment]
Brett,

> A third party AD19 user does not see any damage/problems with new 1024?

Honestly I don't know. I'd take your script as is even if it doesn't support the full set of AD features. But I think it's important to mention it in a README file.
Can I re-open the PR?

About version compatibility I'm not against integrating your version of the script: storing a script which works only with the last version of Altium Designer is better than having a script which is valid only for older versions! Plus older versions of the script stay accessible through the GitHub log.
By the way the compatibility of the scripts amongst different AD versions really sucks :unamused:. If you now a good way to detect AD version from inside the script code I'd love to see how you do.

I think you're right about "why users don't use scripts".
Since I'm the maintainer of [this script library](https://github.com/Altium-Designer-addons/scripts-libraries) I tried to add some ease for newcomers on how to download and use the scripts:
* with a [wiki page "how to start"](https://github.com/Altium-Designer-addons/scripts-libraries/wiki/HowTo_execute_scripts)
* with the direct download links from the README

**I would consider all your suggestions on how to improve "access" to our scripts base.**

Thanks for your work on the forums, I'm [not much active](https://userprofile.live.altium.com/#user/D166D8AB-0928-47E4-BB29-41F33177EA65) on them. I'm tired of how they are abandoned by Altium, just as the BugCrunch platform is useless. I was [active at submitting bugs](https://userprofile.live.altium.com/#user/48214161-EEDE-49BA-AB76-55B6194E19A1) at a time but user tickets are mostly not considered...

**Comment by BrettLMiller** [comment]
Justin,

Finding version from scripting API is easy.

Client.GetProductVersion;
There's a whole raft of similar version strings..

My MechLayerName-test.pas logs this version string in the report file so can try
to understand the internal changes. Hasn't helped so far..

But I don't think the scripting API has changed in many years..the enumerated
consts/types in the API are plain wrong, even for AD17.

I have multiple support cases open around the Layers/LayerStack interfaces etc.
These have been escalated to the internal bug triage system.

Brett.

**Comment by justinmassiot** [comment]
OK now I understand:

* AD 19.1.5 -> Client.GetProductVersion = 19.1.5.86 :heavy_check_mark:
* AD 17.1.9 -> Client.GetProductVersion = 17.1.9.592 :heavy_check_mark:
* AD 16.1.12 -> Client.GetProductVersion = 16.1.12.290 :heavy_check_mark:
* AD 14.3.20 -> Client.GetProductVersion = 10.0.0.30000 :x: (either with DelphiScript, VBScript or JavaScript)
* _AD 13 and before -> I don't have those versions installed any more. I think to recall a version in which GetProductVersion gave the version of the script interpreter engine._

My first developments were with AD 13 and AD 14 and I suppose I may have stayed with the feeling that we couldn't properly get the Altium Designer version from a script. Thank you for the update.
I will try to update my own scripts with a version detection and block the execution or warn the user if I know about an incompatibility.

What about your modifications? Should we integrate them or not?

**Comment by BrettLMiller** [comment]
AFAICK

Prior to AD14 had to read an ini file for version:

  //Check AD version for layer stack version
   VersionStr:= ReadStringFromIniFile('Preference
Location','Build',SpecialFolder_AltiumSystem+'\PrefFolder.ini','14');
   S := Copy(VersionStr,0,2);
   //ShowMessage(S);
   MajorADVersion := StrToInt(S);

   if MajorADVersion >= 14 then
      TheLayerStack := Board.LayerStack_V7;   // v1.8 for AD14

   if MajorADVersion < 14 then
      TheLayerStack := Board.LayerStack;      // v1.8 for Older Versions of AD


LayerStack_V7 interface is still the most functional.
I believed scripting API to be 5 years out-of-date & the above does support that
assertion.
So AD14 to AD19 appear to have mostly unchanged scripting API w.r.t. layerstack.

So AIUI my changes to MechLayerNames were only fixing what did not work properly
& using colour names instead of raw BGR & adding mech layer pairs.

I do not have a AD19 install available to be able to test support. 

BrettM

**Pull request closed without merging**
