### PR TITLE
New short script for SCHLib

### PR DESCRIPTION
**Pull request by igorpnk**
A new short script for changing the link to the footprint library in the models in the components in the SCHLib library.

### CODE REVIEW

**Comment by justinmassiot** [comment]
Thanks Igor for your contribution.
I'm sorry but from your script description I don't really get what does your script aim at. Could you please try to rephrase?

**Comment by igorpnk** [comment]
For each component in the SCHLib library, a footprint is assigned and the path to the PCBLib library from which this footprint is taken is assigned.
Sometimes you need to change the PCBLib library. For example, a copy is made and you need to change the address to a new library.
It is precisely when working with SCHLib and PCBLib.
The script allows you to specify the path to the new PCBLib library and replace the address for all footprints of all components in SCHLib.

**Comment by igorpnk** [comment]
This approach to working with libraries is not desirable, but it turned out that sometimes some work just that way. Actually this script was created on request for the automation of manual reassignment of the address to the library PCBLib. 
You can even add a tag to this script: Not recommended.

**Comment by justinmassiot** [comment]
Igor,
Did you intentionally close this issue? Nothing is merged at the moment.

**Comment by igorpnk** [comment]
Yes, this script is too insignificant :) Maybe you really should not shove it into a common repository.

**Comment by justinmassiot** [comment]
What about keeping it in the "Examples" section?

**Comment by igorpnk** [comment]
This script was made following the example of the OpenLib script. Therefore, he does not even draw on an example :)

**Comment by igorpnk** [comment]
For use as an example, I have a rather large script: https://github.com/igorpnk/ADtoTopor
But there is used the Russian language in the comments.

**Pull request closed without merging**
