### PR TITLE
update to v3.1 circa 2014-2016 found in AD forums?

### PR DESCRIPTION
**Pull request by BrettLMiller**
Justin, this PR just provides the latest copy (v3.1) that  I found (2016) in the AD forums. It solves the immediate problem of not working at all. It works in AD17 & AD20. I plan to make some other changes to support 1024 mech layers etc.

I did not realise my later commits would be added to this pull request, that was never the intention.. you can delete this pull request.

### CODE REVIEW

**Comment by justinmassiot** [comment]
@BrettLMiller , should I remove all of the 4 commits you added at a second time?

**Comment by justinmassiot** [comment]
What about making this PR targetting issue #55 , and creating an other PR for issues #49 and #50 ?

**Comment by BrettLMiller** [comment]
@justinmassiot  Only pull the commits directly related to CopyDesignatorsToMechLayerPair 
7e22da2
2b721f4

I haven't finished making changes to AdjustDesignators2.

**Comment by justinmassiot** [comment]
I've finally gathered the three commits related to `CopyDesignatorsToMechLayerPair` (7e22da24b58999c3b9eb4a8d1c183ae2bda83236, cefebef03a33e6938b0eeaf20199639de35f6da2, 2b721f43b4a1c0ab0086e84a66eb01d2c4000fa8) into a new Pull Request #60.
Feel free to open a new PR if you have a fix for AdjustDesignators2.

**Pull request closed without merging**
