### PR TITLE
Initial commit of Create/PlaceDashedLines.pas

### PR DESCRIPTION
**Pull request by BrettLMiller**
Was posted to AD forums some weeks back.
Script has existed for quite some time.
I tweaked the UI loops to make it bit easier to use.
Cleaned the code a bit & sped up the random union-index generation.

### CODE REVIEW

**Comment by justinmassiot** [comment]
Hey @BrettLMiller! Welcome to the project and thanks for your work.

> Script has existed for quite some time.

Could you please tell us approximately when? Did you store the script on your side from that date?

Would you also please edit the [README.md](https://github.com/Altium-Designer-addons/scripts-libraries/blob/master/README.md) file with a description and the download link in order for our visitors to directly download individual projects?
Thanks very much in advance 👍

**Comment by BrettLMiller** [comment]
Justin
I was asked by Altium forum user to tweak the UI couple (3?) weeks ago.
I did not have and did not ever use that script before that date.
I have located the original post on [forum](https://forum.live.altium.com/#posts/71589/182889)

Can you edit the README.md with gedit/notepad++ etc ?
I don't know how to put URL link in that file that will work after/if you accept this pull request.

**Comment by justinmassiot** [comment]
OK I understand.

> Can you edit the README.md with gedit/notepad++ etc ?

Yes of course. You also have an interactive graphical editor on the GitHub web interface!

> I don't know how to put URL link in that file that will work after/if you accept this pull request.

You did well with [your commit on FormatCopy](https://github.com/Altium-Designer-addons/scripts-libraries/pull/34/commits/81b16eefda46b66940200b378dbeb480315e6b96) from your [formatcopy branch](https://github.com/BrettLMiller/scripts-libraries/tree/formatcopy) (PR #34).

**Comment by BrettLMiller** [comment]
Decided that "Create" was to emotive/suggestive & the folder is best named "PlaceDashedLines" after the script PlaceDashedLine.pas.
Altium uses "Place object" nomenclature for similar built-in operations.

**Comment by BrettLMiller** [comment]
Thanks @justinmassiot 

BrettM.

**Pull request merged**
