### PR TITLE
SpiralTrack Update

### PR DESCRIPTION
**Pull request by igorpnk**
The basic function has been added to the project and the board file has been updated to the current version.
P.S.
This is my first request, please do not judge strictly.

### CODE REVIEW

**Comment by justinmassiot** [comment]
Hello @igorpnk and thank you for your input.
You didn't update the script source file (*.vbs), is it intentional?

> the board file has been updated to the current version

Current version of the script? Current version of Altium Designer?

**Comment by igorpnk** [comment]
Hello!
I did not update the script code because even in the latest versions of the AD, it works as intended.
But when testing this script in the SpiralTest.PcbDoc file, an additional warning file appears in the latest versions of AD. I decided to update the file version so that an error would not appear.
Additionally, I fixed the link to the starting procedure in the project file so that the script would be launched only by selecting the script project.
Since I want to use this script as a demo, I would like to make the above corrections.

Used AD version 20.

**Comment by justinmassiot** [comment]
> an additional warning file appears in the latest versions of AD

What if I want to use an older version of AD?

**Comment by igorpnk** [comment]
In older versions of AD, the printed circuit board will open correctly, but with an additional message that the file is in a new format with a description of the innovations.

**Comment by justinmassiot** [comment]
You're right. I was just wondering if it was better to keep an old file and let users have AD upgrade it, or if we should have the "most up-to-date file" and count on the AD backward compatibility for users with older versions of AD.\
Anyway, that's not really important because both cases work.

**Comment by igorpnk** [comment]
There are many more users in the new version of HELL than in the old one. When generating a new file, git immediately sees it as a change and wants to commit. Whatever this happens for most users, I decided to update the version of this file.

**Pull request merged**
